name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    types: [opened]

jobs:
  check-PR-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          TITLE: ${{ github.event.pull_request.title }}
          DRAFT: "draft:"
      - run: |
          echo The Title of your PR is "$TITLE"
          if [[ $TITLE == $DRAFT* ]]; then
            echo "It's there!"
          fi
