name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-PR-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo The Title of your PR is ${{ github.event.pull_request.title }}
