name: Check if the PR is draft

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check-PR-title:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - id: checkPrTitle
        name: check PR title
        run: |
          title="${{ github.event.pull_request.title }}"
          draft="draft:"
          echo "isDraft=false" >> "$GITHUB_OUTPUT"
          if [[ $title == draft:* ]]; then
            echo "It's there!"
            echo "isDraft=true" >> "$GITHUB_OUTPUT"
          fi

      - name: change PR status
        run: |
          isDraft=${{ steps.checkPrTitle.outputs.isDraft }}
          if [[ $isDraft == true ]]; then
            gh pr ready ${{ github.event.pull_request.number }} --undo
          else
            gh pr ready ${{ github.event.pull_request.number }}
          fi
