name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check-PR-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          title="${{ github.event.pull_request.title }}"
          draft="draft:"
          echo The Title of your PR is $title
          if [[ $title == draft:* ]]; then
            echo "It's there!"
          fi
