name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check-PR-title:
    runs-on: ubuntu-latest
    outputs:
      isDraft: ${{ steps.checkPrTitle.outputs.isDraft }}
    steps:
      - uses: actions/checkout@v4

      - id: checkPrTitle
        name: check PR title
        run: |
          title="${{ github.event.pull_request.title }}"
          draft="draft:"
          echo The Title of your PR is $title
          if [[ $title == draft:* ]]; then
            echo "It's there!"
            echo "isDraft=true" >> "$GITHUB_OUTPUT"
          fi

  change-PR-status:
    runs-on: ubuntu-latest
    needs: check-PR-title
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: change PR status
        run: |
          isDraft=${{ needs.check-PR-title.outputs.isDraft }}
          if [[ isDraft ]]; then
            echo "it;s draftt"
            gh pr ready ${{ github.event.pull_request.node_id }} --undo
          fi
