name: Draft PR on Push

on:
  push:
    branches: [main]

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check PR title
        run: |
          title=$(git rev-parse --abbrev-ref HEAD)^!/$GITHUB_HEAD_REF 
          if [[ $title == draft:* ]]; then
            echo "This PR is a draft."
            gh pr create --title "$title" --body "" --draft
          fi

      - uses: actions/github-script@v6
        with:
          github-script: |
            github.issues.createPullRequest({
              title: context.ref,
              head: context.ref,
              base: 'main',
              draft: ${{ contains(github.event.pull_request.title, 'draft: ') }}
            })
